FROM beevelop/cordova:v8.0.0

RUN apt-get update && \
    apt-get install -y python \
                       build-essential \
                       libfontconfig \
		       imagemagick &&\
    rm -rf /var/lib/apt/lists/*

WORKDIR /

RUN npm i -g npm
COPY package.json package.json
RUN npm install

RUN ln -f -s /node_modules/.bin/* /usr/local/bin/
WORKDIR /app